[package]
name = "language_parse_tree"
version = "0.1.0"
edition = "2021"
author = "Nojipiz"

[dependencies]
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
debug_tree = "0.4.0"
